# Generated by Django 4.0.5 on 2022-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(blank=True, db_column='Institute', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=60, null=True)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
                ('field', models.TextField(blank=True, db_column='Field', null=True)),
            ],
            options={
                'db_table': 'uni_courses',
                'managed': False,
            },
        ),
    ]
