# Generated by Django 4.0.5 on 2022-09-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_unicourses_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unicourses',
            table='uni_courses',
        ),
    ]
